drop table if exists postData CASCADE;
create table postData
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(1000000000),
    time varchar(30),
    type varchar(30),
    viewCount bigint,
    postLike bigint,
    disLike bigint,
    primary key (id)
);