drop table if exists postData CASCADE;
create table postData
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(1000000000),
    time varchar(30),
    type varchar(30),
    viewCount bigint,
    postLike bigint,
    disLike bigint,
    primary key (id)
);

create table POST_IMAGE
(
    key varchar(255),
    post_id bigint,
    primary key (key),
    foreign key (post_id) references post_data (id) on delete cascade
);